networks:
  team07:
    external: true

services:
  tokengram-frontend:
    build: .
    container_name: tokengram-frontend
    image: tokengram-frontend
    restart: unless-stopped
    ports:
      - ${TOKENGRAM_FRONTEND_HOST_PORT:-6000}:3000
    networks:
      - team07
