version: '1.0'

networks:
  team07:
    external: true

services:
  tokengram-frontend:
    build: .
    container_name: tokengram-frontend
    image: tokengram-frontend
    restart: unless-stopped
    ports:
      - 3000:3000
    networks:
      - team07
